Fix the tests-passed job (#1613)

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -256,12 +256,20 @@ jobs:
         run: python -m pytest --cov=. --cov-report=xml --cov-report=term-missing tests
         if: "!cancelled()"
 
-  # Empty job so that github can gate PR merge
+  # Sink job so that github can gate PR merge
   tests-passed:
     runs-on: ubuntu-22.04
+    if: ${{ always() }}
     needs:
       - lint
       - run-unit-tests
       - e2e
     steps:
-      - run: echo "Tests passed!"
+      - name: Tests Failed
+        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
+        run: |
+          echo "Tests failed!"
+          exit 1
+      - name: Tests Succeeded
+        run: |
+          echo "Tests succeeded!"
